jwt:
  secret: als2fg(__s

spring:
  datasource:
    url: jdbc:mysql://localhost/social_network
    username: user
    password: password
#flyway.baseline-on-migrate=true #used if database has some already table
#flyway:
  #enabled: true
  #url: jdbc:mysql://localhost/social_network
  #user: root
  #password: